# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cfccb024582d0d4a019f8710b76a45bdd10bca0a0ff35aec5c221983b1a02e11b75a6c45f66ae2bed9fc912c17fb97c42a52ae72a7697cb957ca8130756baca8

test:
  secret_key_base: c0331f04e6cb0ae3a122a3f60686911ed7dfe649feeab6d6b4e710bfe601e58f1a2580b72bd2ffa018c2f5f8651271363c52e52da9e8857edd85a548031f01c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
